services:
  - type: web
    name: real-estate-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: REST_API_PORT
        value: 3002
      - key: API_BASE_URL
        sync: false
      - key: INMUEBLES24_API_KEY
        sync: false
      - key: VIVANUNCIOS_API_KEY
        sync: false
      - key: EASYBROKER_API_KEY
        sync: false